### ISSUE TITLE
torchvision-dependent code breaks for version `0.11.3+cu113`

### ISSUE THREAD

**Issue by lxuechen** [MadryLab/robustness#113]
Running simple checks, I get

```
Traceback (most recent call last):
  File "breeds_check.py", line 5, in <module>
    from robustness import datasets
  File "/opt/conda/envs/explainx/lib/python3.8/site-packages/robustness/datasets.py", line 22, in <module>
    from . import imagenet_models, cifar_models
  File "/opt/conda/envs/explainx/lib/python3.8/site-packages/robustness/imagenet_models/__init__.py", line 3, in <module>
    from .vgg import *
  File "/opt/conda/envs/explainx/lib/python3.8/site-packages/robustness/imagenet_models/vgg.py", line 3, in <module>
    from torchvision.models.utils import load_state_dict_from_url
ModuleNotFoundError: No module named 'torchvision.models.utils'
```

Related issues [here](https://github.com/xingyizhou/CenterTrack/issues/134) and [here](https://stackoverflow.com/questions/70998767/no-module-named-torchvision-models-utils).

**Comment by lxuechen** [comment]
Just a note that this doesn't appear to be an issue in `main`. Installing via pip defaults to the last tag, which has this issue.
