### ISSUE TITLE
TypeError: append() got an unexpected keyword argument 'table'

### ISSUE THREAD

**Issue by LokLu** [MadryLab/robustness#35]
Env:
torch==1.1.0
torchvision=0.3.0
cuda=10
Command running:
python3 -m robustness.main --dataset cifar --data ./data/cifar10/by-image --adv-train 0 --arch resnet50 --out-dir ./logs/
Error got:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/robustness/main.py", line 112, in <module>
    store = setup_store_with_metadata(args)
  File "/workspace/robustness/main.py", line 103, in setup_store_with_metadata
    store['metadata'].append_row(args_dict)
  File "/opt/conda/lib/python3.6/site-packages/cox/store.py", line 296, in append_row
    self.flush_row()
  File "/opt/conda/lib/python3.6/site-packages/cox/store.py", line 416, in flush_row
    self._HDFStore.append(self._name, df, table=True)
TypeError: append() got an unexpected keyword argument 'table'

Seems like a cox library error?

**Comment by margiki** [comment]
It's because you use a newer version of Pandas (1.0+). Downgrading to Pandas 0.25.3 should solve your issue :)

**Comment by LokLu** [comment]
@margiki Thanks, solved by downgrading the pandas lib.
